<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scala</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(\{\s*(//.*)?$|^\s*// \{\{\{)</string>
	<key>foldingStopMarker</key>
	<string>^\s*(\}|// \}\}\}$)</string>
	<key>name</key>
	<string>Scala</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\)|\}|[A-Za-z0-9]|\s):\s</string>
			<key>end</key>
			<string>(?=\)|(=)|\n|,|(;(\s)*\n))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{(?&lt;balanced&gt;[^\{\}]|\{\g&lt;balanced&gt;*\})*\}</string>
					<key>name</key>
					<string>storage.type.scala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\((?&lt;balanced&gt;[^\(\)]|\(\g&lt;balanced&gt;*\))*\)</string>
					<key>name</key>
					<string>storage.type.scala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\w|(\[(?&lt;balanced&gt;[^\[\]]|\[\g&lt;balanced&gt;*\])*\])|\W)</string>
					<key>name</key>
					<string>storage.type.scala</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:\)|\}|[A-Za-z0-9]|\s):([A-Za-z])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.scala</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\)|(=)|\n|,|(;(\s)*\n))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{(?&lt;balanced&gt;[^\{\}]|\{\g&lt;balanced&gt;*\})*\}</string>
					<key>name</key>
					<string>storage.type.scala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\((?&lt;balanced&gt;[^()]|\(\g&lt;balanced&gt;*\))*\)</string>
					<key>name</key>
					<string>storage.type.scala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\w|(\[(?&lt;balanced&gt;[^\[\]]|\[\g&lt;balanced&gt;*\])*\])|\W)</string>
					<key>name</key>
					<string>storage.type.scala</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)([LlFfUuDd]|UL|ul)?\b</string>
			<key>name</key>
			<string>constant.numeric.scala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(catch|do|extends|false|finally|forSome|implicit|lazy|match|null|protected|private|requires|sealed|super|this|throw|try|true|type|with|yield|new|package|override|import|abstract|class|object|case|trait|final|def|val|var|if|else|while|for|return)\b</string>
			<key>name</key>
			<string>keyword.control.untitled.scala</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.scala</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.scala</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.scala</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.scala</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.scala</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.scala</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.scala</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.scala</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.scala</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'|(\w(\s|\W))</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.scala</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.scala</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.scala</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.scala</string>
	<key>uuid</key>
	<string>35C312BB-639C-47AB-86B1-ECFFC47FB7F0</string>
</dict>
</plist>
